package selenium;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class CreateNewArticleTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @ParameterizedTest
    @ValueSource(classes = {ChromeDriver.class, FirefoxDriver.class})
    public void createNewArticle(Class<? extends WebDriver> webDriverClass) {
        // Test name: Create New Article
// Driver management and WebDriver instantiation
        driver = WebDriverManager.getInstance(webDriverClass).create();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost:8081/articles");
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));
        // 2 | setWindowSize | 1722x936 |
        driver.manage().window().setSize(new Dimension(1722, 936));
        // 3 | click | linkText=Add Article |
        driver.findElement(By.linkText("Add Article")).click();
        // 4 | click | id=title |
        driver.findElement(By.id("title")).click();
        // 5 | type | id=title | Selenium IDE
        driver.findElement(By.id("title")).sendKeys("Selenium IDE");
        // 6 | click | id=content |
        driver.findElement(By.id("content")).click();
        // 7 | type | id=content | Selenium IDE is easy to use
        driver.findElement(By.id("content")).sendKeys("Selenium IDE is easy to use");
        // 8 | click | id=file |
//        driver.findElement(By.id("file")).click();
        // 9 | type | id=file | C:\Users\office27\Pictures\java2days.png
        driver.findElement(By.id("file")).sendKeys("C:\\Users\\office27\\Pictures\\java2days.png");
        // 10 | click | id=submit |
        driver.findElement(By.id("submit")).click();
        // 11 | click | xpath=//tr[last()]/td[6]/a/img |
        driver.findElement(By.xpath("//tr[last()]/td[6]/a/img")).click();
        // 12 | mouseOver | css=tr:last-child .img-thumbnail |
        {
            WebElement element = driver.findElement(By.cssSelector("tr:last-child .img-thumbnail"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 13 | mouseOut | css=tr:last-child .img-thumbnail |
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 14 | click | css=.btn-secondary |
        driver.findElement(By.cssSelector(".btn-secondary")).click();
    }
}
